version: '3.8'

services:
  php-appache:
    build: .                  # Указываем путь к Dockerfile
    ports:
      - "8080:80"             # Перенаправляем локальный порт 8080 на порт 80 контейнера
    volumes:
      - ./app:/var/www/html   # Привязываем папку app к /var/www/html в контейнере
      - ./app/vendor:/var/www/html/vendor
    depends_on:
      - db                    # Указываем зависимость от сервиса db

  db:
    image: mysql:8.0          # Используем официальный образ MySQL
    container_name: mysql-db  # Имя контейнера
    restart: always           # Автоматический перезапуск
    environment:              # Настраиваем переменные среды
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"           # Перенаправляем порт для подключения к MySQL
    volumes:
      - db_data:/var/lib/mysql # Храним данные MySQL на локальном диске

volumes:
  db_data:                    # Определяем volume для хранения данных MySQL
